export default [
  {
    avatarIcon: 'bob.png',
    userName: 'Spacex',
    handle: 'spacex',
    time: '23h',
    webURL: 'http://google.com',
    post: 'Dennis and Akkio Tito are the first two members on the starhip second commercial spaceflight around the moon.',
    details: {
      title: 'Countdown: Inspiration4 mission to space | Netflix Official Site',
      description: 'From training to launch to landing, this all-access docuseries rides along with the inpiration4 on the first all-civillian orbital space...',
    },
    image: 'banner.jpeg',
    comments: "4.2K",
    retweets: '3.5K',
    likes: '37.5K',
  },
  {
    avatarIcon: 'dp.jpeg',
    userName: 'New York Post',
    handle: 'nypost',
    time: '23h',
    webURL: 'http://tribe.al/nx2Gfaq',
    post: 'Grime seen reading Karl Marx following split with world\'s richest man Elon Musk',
    image: 'banner-2.jpeg',
    comments: "965",
    retweets: '2.4K',
    likes: '4K',
  },
];
